export const ActionTypes = {
    SET_MOVIES: 'SET_MOVIES',
    SELECTED_MOVIE: 'SELECTED_MOVIE',
    REMOVE_SELECTED_MOVIE: 'REMOVE_SELECTED_MOVIE',
    SET_SHOWS: 'SET_SHOWS',
    SELECTED_SHOW: 'SELECTED_SHOW',
    REMOVE_SELECTED_SHOW: 'REMOVE_SELECTED_SHOW',
}